In [7]:
import pandas as pd
import numpy as np
path = r'D:\Next Hikes\Project 1\dataset_1.xlsx'
data = pd.read_excel(path)
data.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,1,2011-01-01,1,0,1,0,False,6,1,0.24
1,2,2011-01-01,1,0,1,1,False,6,1,0.22
2,3,2011-01-01,1,0,1,2,False,6,1,0.22
3,4,2011-01-01,1,0,1,3,False,6,1,0.24
4,5,2011-01-01,1,0,1,4,False,6,1,0.24

In [63]:
# To get the first 5 rows
data.tail()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
605,606,2011-01-28,1,0,1,11,False,5,3,0.18
606,607,2011-01-28,1,0,1,12,False,5,3,0.18
607,608,2011-01-28,1,0,1,13,False,5,3,0.18
608,609,2011-01-28,1,0,1,14,False,5,3,0.22
609,610,2011-01-28,1,0,1,15,False,5,2,0.20

In [64]:
# To get the first 20 rows
data.head(20)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,1,2011-01-01,1,0,1,0,False,6,1,0.24
1,2,2011-01-01,1,0,1,1,False,6,1,0.22
2,3,2011-01-01,1,0,1,2,False,6,1,0.22
3,4,2011-01-01,1,0,1,3,False,6,1,0.24
4,5,2011-01-01,1,0,1,4,False,6,1,0.24
5,6,2011-01-01,1,0,1,5,False,6,2,0.24
6,7,2011-01-01,1,0,1,6,False,6,1,0.22
7,8,2011-01-01,1,0,1,7,False,6,1,0.20
8,9,2011-01-01,1,0,1,8,False,6,1,0.24
9,10,2011-01-01,1,0,1,9,False,6,1,0.32
10,11,2011-01-01,1,0,1,10,False,6,1,0.38
11,12,2011-01-01,1,0,1,11,False,6,1,0.36
12,13,2011-01-01,1,0,1,12,False,6,1,0.42
13,14,2011-01-01,1,0,1,13,False,6,2,0.46
14,15,2011-01-01,1,0,1,14,False,6,2,0.46
15,16,2011-01-01,1,0,1,15,False,6,2,0.44
16,17,2011-01-01,1,0,1,16,False,6,2,0.42
17,18,2011-01-01,1,0,1,17,False,6,2,0.44
18,19,2011-01-01,1,0,1,18,False,6,3,0.42
19,20,2011-01-01,1,0,1,19,False,6,3,0.42

In [8]:
#to get the bottom 20 rows
data.tail(20)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
590,591,2011-01-27,1,0,1,19,False,4,1,0.20
591,592,2011-01-27,1,0,1,20,False,4,1,0.18
592,593,2011-01-27,1,0,1,21,False,4,1,0.18
593,594,2011-01-27,1,0,1,22,False,4,1,0.18
594,595,2011-01-27,1,0,1,23,False,4,1,0.18
595,596,2011-01-28,1,0,1,0,False,5,2,0.20
596,597,2011-01-28,1,0,1,1,False,5,2,0.20
597,598,2011-01-28,1,0,1,2,False,5,2,0.20
598,599,2011-01-28,1,0,1,3,False,5,2,0.20
599,600,2011-01-28,1,0,1,5,False,5,2,0.18
600,601,2011-01-28,1,0,1,6,False,5,2,0.18
601,602,2011-01-28,1,0,1,7,False,5,2,0.16
602,603,2011-01-28,1,0,1,8,False,5,2,0.16
603,604,2011-01-28,1,0,1,9,False,5,3,0.18
604,605,2011-01-28,1,0,1,10,False,5,3,0.18
605,606,2011-01-28,1,0,1,11,False,5,3,0.18
606,607,2011-01-28,1,0,1,12,False,5,3,0.18
607,608,2011-01-28,1,0,1,13,False,5,3,0.18
608,609,2011-01-28,1,0,1,14,False,5,3,0.22
609,610,2011-01-28,1,0,1,15,False,5,2,0.20

In [14]:
# To get the dimesnion of the data
data.shape

(610, 10)

In [30]:
data.describe()

,instant,dteday,season,yr,mnth,hr,weekday,weathersit,temp
count,610.000000,610,610.0,610.0,610.0,610.000000,610.000000,610.000000,610.000000
mean,305.500000,2011-01-13 19:47:24.590163968,1.0,0.0,1.0,11.795082,2.977049,1.477049,0.196885
min,1.000000,2011-01-01 00:00:00,1.0,0.0,1.0,0.000000,0.000000,1.000000,0.020000
25%,153.250000,2011-01-07 00:00:00,1.0,0.0,1.0,6.000000,1.000000,1.000000,0.160000
50%,305.500000,2011-01-14 00:00:00,1.0,0.0,1.0,12.000000,3.000000,1.000000,0.200000
75%,457.750000,2011-01-21 00:00:00,1.0,0.0,1.0,18.000000,5.000000,2.000000,0.235000
max,610.000000,2011-01-28 00:00:00,1.0,0.0,1.0,23.000000,6.000000,4.000000,0.460000
std,176.236111,NaN,0.0,0.0,0.0,6.852107,2.054943,0.643496,0.081304

In [31]:
data.describe(include='all')

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
count,610.000000,610,610.0,610.0,610.0,610.000000,610,610.000000,610.000000,610.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,586,NaN,NaN,NaN
mean,305.500000,2011-01-13 19:47:24.590163968,1.0,0.0,1.0,11.795082,NaN,2.977049,1.477049,0.196885
min,1.000000,2011-01-01 00:00:00,1.0,0.0,1.0,0.000000,NaN,0.000000,1.000000,0.020000
25%,153.250000,2011-01-07 00:00:00,1.0,0.0,1.0,6.000000,NaN,1.000000,1.000000,0.160000
50%,305.500000,2011-01-14 00:00:00,1.0,0.0,1.0,12.000000,NaN,3.000000,1.000000,0.200000
75%,457.750000,2011-01-21 00:00:00,1.0,0.0,1.0,18.000000,NaN,5.000000,2.000000,0.235000
max,610.000000,2011-01-28 00:00:00,1.0,0.0,1.0,23.000000,NaN,6.000000,4.000000,0.460000
std,176.236111,NaN,0.0,0.0,0.0,6.852107,NaN,2.054943,0.643496,0.081304

In [37]:
data.dropna(axis =0, inplace=True)

In [43]:
data.describe(include='all')

          instant
count  610.000000
mean   305.500000
std    176.236111
min      1.000000
25%    153.250000
50%    305.500000
75%    457.750000
max    610.000000

In [52]:
data.reset_index()

     level_0  index  instant
0          0      0        1
1          1      1        2
2          2      2        3
3          3      3        4
4          4      4        5
..       ...    ...      ...
605      605    605      606
606      606    606      607
607      607    607      608
608      608    608      609
609      609    609      610

[610 rows x 3 columns]

In [54]:
data.shape

(610, 3)

In [57]:
print(data.columns)

Index(['level_0', 'index', 'instant'], dtype='object')

In [58]:
print(data.head())

   level_0  index  instant
0        0      0        1
1        1      1        2
2        2      2        3
3        3      3        4
4        4      4        5

In [9]:

columns_to_retrieve = ['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'weathersit', 'temp']
retrieved_columns = data[columns_to_retrieve]

# If you dropped rows, you can retrieve them using the original indices
# Assuming 'indices_to_retrieve' is a list of indices that were dropped

In [67]:
data.describe()

,instant,dteday,season,yr,mnth,hr,weekday,weathersit,temp
count,610.000000,610,610.0,610.0,610.0,610.000000,610.000000,610.000000,610.000000
mean,305.500000,2011-01-13 19:47:24.590163968,1.0,0.0,1.0,11.795082,2.977049,1.477049,0.196885
min,1.000000,2011-01-01 00:00:00,1.0,0.0,1.0,0.000000,0.000000,1.000000,0.020000
25%,153.250000,2011-01-07 00:00:00,1.0,0.0,1.0,6.000000,1.000000,1.000000,0.160000
50%,305.500000,2011-01-14 00:00:00,1.0,0.0,1.0,12.000000,3.000000,1.000000,0.200000
75%,457.750000,2011-01-21 00:00:00,1.0,0.0,1.0,18.000000,5.000000,2.000000,0.235000
max,610.000000,2011-01-28 00:00:00,1.0,0.0,1.0,23.000000,6.000000,4.000000,0.460000
std,176.236111,NaN,0.0,0.0,0.0,6.852107,2.054943,0.643496,0.081304

In [68]:
data.describe(include='all')

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
count,610.000000,610,610.0,610.0,610.0,610.000000,610,610.000000,610.000000,610.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,586,NaN,NaN,NaN
mean,305.500000,2011-01-13 19:47:24.590163968,1.0,0.0,1.0,11.795082,NaN,2.977049,1.477049,0.196885
min,1.000000,2011-01-01 00:00:00,1.0,0.0,1.0,0.000000,NaN,0.000000,1.000000,0.020000
25%,153.250000,2011-01-07 00:00:00,1.0,0.0,1.0,6.000000,NaN,1.000000,1.000000,0.160000
50%,305.500000,2011-01-14 00:00:00,1.0,0.0,1.0,12.000000,NaN,3.000000,1.000000,0.200000
75%,457.750000,2011-01-21 00:00:00,1.0,0.0,1.0,18.000000,NaN,5.000000,2.000000,0.235000
max,610.000000,2011-01-28 00:00:00,1.0,0.0,1.0,23.000000,NaN,6.000000,4.000000,0.460000
std,176.236111,NaN,0.0,0.0,0.0,6.852107,NaN,2.054943,0.643496,0.081304

In [10]:
data.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     610 non-null    int64
 1   dteday      610 non-null    datetime64[ns]
 2   season      610 non-null    int64
 3   yr          610 non-null    int64
 4   mnth        610 non-null    int64
 5   hr          610 non-null    int64
 6   holiday     610 non-null    bool
 7   weekday     610 non-null    int64
 8   weathersit  610 non-null    int64
 9   temp        610 non-null    float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(7)
memory usage: 43.6 KB

In [73]:
data["instant"].value_counts()

instant
1      1
410    1
403    1
404    1
405    1
      ..
205    1
206    1
207    1
208    1
610    1
Name: count, Length: 610, dtype: int64

In [74]:
data.dtypes

instant                int64
dteday        datetime64[ns]
season                 int64
yr                     int64
mnth                   int64
hr                     int64
holiday                 bool
weekday                int64
weathersit             int64
temp                 float64
dtype: object

In [78]:
data

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,1,2011-01-01,1,0,1,0,False,6,1,0.24
1,2,2011-01-01,1,0,1,1,False,6,1,0.22
2,3,2011-01-01,1,0,1,2,False,6,1,0.22
3,4,2011-01-01,1,0,1,3,False,6,1,0.24
4,5,2011-01-01,1,0,1,4,False,6,1,0.24
...,...,...,...,...,...,...,...,...,...,...
605,606,2011-01-28,1,0,1,11,False,5,3,0.18
606,607,2011-01-28,1,0,1,12,False,5,3,0.18
607,608,2011-01-28,1,0,1,13,False,5,3,0.18
608,609,2011-01-28,1,0,1,14,False,5,3,0.22
609,610,2011-01-28,1,0,1,15,False,5,2,0.20

In [86]:
data.isnull()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
605,False,False,False,False,False,False,False,False,False,False
606,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False
609,False,False,False,False,False,False,False,False,False,False

In [88]:
data.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [93]:
data.dropna(inplace = True)

In [94]:
data.shape

(610, 10)

In [98]:
# checking if the column is dropped or not
if 'yr' not in data.columns:
    print("Column 'yr' has been successfully dropped.")
else:
    print("Column 'yr' is still present in the DataFrame.")

Column 'yr' has been successfully dropped.

In [99]:
data.describe

<bound method NDFrame.describe of      instant     dteday  season  mnth  hr  holiday  weekday  weathersit  temp
0          1 2011-01-01       1     1   0    False        6           1  0.24
1          2 2011-01-01       1     1   1    False        6           1  0.22
2          3 2011-01-01       1     1   2    False        6           1  0.22
3          4 2011-01-01       1     1   3    False        6           1  0.24
4          5 2011-01-01       1     1   4    False        6           1  0.24
..       ...        ...     ...   ...  ..      ...      ...         ...   ...
605      606 2011-01-28       1     1  11    False        5           3  0.18
606      607 2011-01-28       1     1  12    False        5           3  0.18
607      608 2011-01-28       1     1  13    False        5           3  0.18
608      609 2011-01-28       1     1  14    False        5           3  0.22
609      610 2011-01-28       1     1  15    False        5           2  0.20

[610 rows x 9 columns]>

In [100]:
data.head

<bound method NDFrame.head of      instant     dteday  season  mnth  hr  holiday  weekday  weathersit  temp
0          1 2011-01-01       1     1   0    False        6           1  0.24
1          2 2011-01-01       1     1   1    False        6           1  0.22
2          3 2011-01-01       1     1   2    False        6           1  0.22
3          4 2011-01-01       1     1   3    False        6           1  0.24
4          5 2011-01-01       1     1   4    False        6           1  0.24
..       ...        ...     ...   ...  ..      ...      ...         ...   ...
605      606 2011-01-28       1     1  11    False        5           3  0.18
606      607 2011-01-28       1     1  12    False        5           3  0.18
607      608 2011-01-28       1     1  13    False        5           3  0.18
608      609 2011-01-28       1     1  14    False        5           3  0.22
609      610 2011-01-28       1     1  15    False        5           2  0.20

[610 rows x 9 columns]>

In [4]:
data.to_excel("exported-data.xlsx")

In [5]:
data.to_excel("exported-data1.xlsx")

**Second Dataset**

In [11]:
path = r'D:\Next Hikes\Project 1\dataset_2.xlsx'
dt = pd.read_excel(path)
dt.head()

   Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81        0.0       3          13   16
1           1        2  0.2727  0.80        0.0       8          32   40
2           2        3  0.2727  0.80        0.0       5          27   32
3           3        4  0.2879  0.75        0.0       3          10   13
4           4        5  0.2879  0.75        0.0       0           1    1

In [4]:
dt.head(20)

    Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0            0        1  0.2879  0.81     0.0000       3          13   16
1            1        2  0.2727  0.80     0.0000       8          32   40
2            2        3  0.2727  0.80     0.0000       5          27   32
3            3        4  0.2879  0.75     0.0000       3          10   13
4            4        5  0.2879  0.75     0.0000       0           1    1
5            5        6  0.2576  0.75     0.0896       0           1    1
6            6        7  0.2727  0.80     0.0000       2           0    2
7            7        8  0.2576  0.86     0.0000       1           2    3
8            8        9     NaN  0.75     0.0000       1           7    8
9            9       10  0.3485  0.76     0.0000       8           6   14
10          10       11  0.3939  0.76     0.2537      12          24   36
11          11       12  0.3333  0.81     0.2836      26          30   56
12          12       13  0.4242  0.77     0.2836      29          55   84
13          13       14  0.4545  0.72     0.2985      47          47   94
14          14       15  0.4545  0.72     0.2836      35          71  106
15          15       16  0.4394  0.77     0.2985      40          70  110
16          16       17  0.4242  0.82     0.2985      41          52   93
17          17       18     NaN  0.82     0.2836      15          52   67
18          18       19  0.4242  0.88     0.2537       9          26   35
19          19       20  0.4242  0.88     0.2537       6          31   37

In [5]:
dt.tail(20)

     Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
590         590      591  0.2273  0.69     0.0896       3          76   79
591         591      592  0.2121  0.74     0.0896       4          55   59
592         592      593  0.2121  0.74     0.0896       2          36   38
593         593      594  0.2121  0.74     0.0896       0          27   27
594         594      595  0.1970  0.80     0.1642       0          16   16
595         595      596  0.2121  0.75     0.1343       0           9    9
596         596      597  0.2121  0.75     0.1343       1           2    3
597         597      598  0.2121  0.75     0.1642       0           2    2
598         598      599  0.2273  0.75     0.1045       1           0    1
599         599      600  0.2121  0.80     0.1045       0           4    4
600         600      601  0.1970  0.80     0.1343       0          16   16
601         601      602  0.1970  0.86     0.0896       2          58   60
602         602      603  0.1970  0.86     0.0896       2         155  157
603         603      604  0.2121  0.86     0.0896       6          95  101
604         604      605  0.2121  0.86     0.1045       0          49   49
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

In [6]:
dt.shape

(610, 8)

In [7]:
dt.describe

<bound method NDFrame.describe of      Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]>

In [8]:
dt.info

<bound method DataFrame.info of      Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]>

In [9]:
dt.describe(include='all')

,Unnamed: 0,instant,atemp,hum,windspeed,casual,registered,cnt
count,610.000000,610.000000,599.000000,610.000000,610.000000,610.000000,610.000000,610.000000
mean,304.500000,305.500000,0.199935,0.562475,0.204851,4.501639,51.068852,55.570492
std,176.236111,176.236111,0.078836,0.175440,0.121806,6.319945,47.021204,49.316802
min,0.000000,1.000000,0.000000,0.210000,0.000000,0.000000,0.000000,1.000000
25%,152.250000,153.250000,0.151500,0.432500,0.104500,0.000000,14.000000,16.000000
50%,304.500000,305.500000,0.197000,0.520000,0.194000,2.000000,43.000000,47.000000
75%,456.750000,457.750000,0.242400,0.690000,0.283600,6.000000,70.000000,79.750000
max,609.000000,610.000000,0.454500,1.000000,0.582100,47.000000,247.000000,249.000000

In [10]:
dt.isnull().sum()

Unnamed: 0     0
instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [12]:
path = r'D:\Next Hikes\Project 1\exported-data.xlsx'
path = r'D:\Next Hikes\Project 1\exported-data1.xlsx'
data = pd.read_excel(path)
data.head()

,Unnamed: 0,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp
0,0,1,2011-01-01,1,0,1,0,False,6,1,0.24
1,1,2,2011-01-01,1,0,1,1,False,6,1,0.22
2,2,3,2011-01-01,1,0,1,2,False,6,1,0.22
3,3,4,2011-01-01,1,0,1,3,False,6,1,0.24
4,4,5,2011-01-01,1,0,1,4,False,6,1,0.24

In [13]:
new_data= pd.merge(data, dt, on = 'instant', how = 'inner')

In [14]:
new_data.isnull()

,Unnamed: 0_x,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,Unnamed: 0_y,atemp,hum,windspeed,casual,registered,cnt
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
606,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
609,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
new_data['yr'].mode()

0    0
Name: yr, dtype: int64

In [16]:
new_data['yr'].value_counts()

yr
0    610
Name: count, dtype: int64

In [17]:
new_data['temp'].median()

0.2

In [18]:
new_data['temp'].mean()

0.19688524590163933

In [16]:
path = r'D:\Next Hikes\Project 1\dataset_3.xlsx'
data_Set3 = pd.read_excel(path)

In [17]:
data_Set3.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,620,2011-01-29,1,0,1,1,False,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,621,2011-01-29,1,0,1,2,False,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,622,2011-01-29,1,0,1,3,False,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,623,2011-01-29,1,0,1,4,False,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,624,2011-01-29,1,0,1,6,False,6,1,0.16,0.1818,0.64,0.1343,0,2,2

In [11]:
data_Set3.tail()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
385,615,2011-01-28,1,0,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
386,616,2011-01-28,1,0,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
387,617,2011-01-28,1,0,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
388,618,2011-01-28,1,0,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
389,619,2011-01-29,1,0,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [21]:
data_Set3.shape

(390, 16)

In [18]:
data_Set3.isnull().iloc[0:25,:]

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
data_Set3.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [20]:
data_Set3.describe(include='all')

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,390.000000,390,390.0,390.0,390.000000,390.000000,390,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,805.500000,2011-02-05 11:45:13.846153728,1.0,0.0,1.800000,11.687179,NaN,2.989744,1.484615,0.220000,0.230424,0.613769,0.179416,5.576923,57.002564,62.579487
min,611.000000,2011-01-28 00:00:00,1.0,0.0,1.000000,0.000000,NaN,0.000000,1.000000,0.060000,0.075800,0.210000,0.000000,0.000000,0.000000,1.000000
25%,708.250000,2011-02-01 00:00:00,1.0,0.0,2.000000,6.000000,NaN,1.000000,1.000000,0.160000,0.181800,0.450000,0.089600,1.000000,17.000000,18.500000
50%,805.500000,2011-02-05 12:00:00,1.0,0.0,2.000000,12.000000,NaN,3.000000,1.000000,0.220000,0.227300,0.600000,0.164200,3.000000,48.000000,52.000000
75%,902.750000,2011-02-10 00:00:00,1.0,0.0,2.000000,18.000000,NaN,5.000000,2.000000,0.260000,0.272700,0.750000,0.283600,6.000000,83.750000,88.750000
max,1000.000000,2011-02-14 00:00:00,1.0,0.0,2.000000,23.000000,NaN,6.000000,3.000000,0.420000,0.424200,1.000000,0.582100,62.000000,236.000000,243.000000
std,112.727548,NaN,0.0,0.0,0.400514,6.980295,NaN,2.149884,0.663805,0.073095,0.069455,0.202361,0.138551,9.317478,49.070198,53.274838

In [26]:
data_Set3.bfill()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,620,2011-01-29,1,0,1,1,False,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,621,2011-01-29,1,0,1,2,False,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,622,2011-01-29,1,0,1,3,False,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,623,2011-01-29,1,0,1,4,False,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,624,2011-01-29,1,0,1,6,False,6,1,0.16,0.1818,0.64,0.1343,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,615,2011-01-28,1,0,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
386,616,2011-01-28,1,0,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
387,617,2011-01-28,1,0,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
388,618,2011-01-28,1,0,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
389,619,2011-01-29,1,0,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [21]:
data_Set3.isnull().sum().sum()

0

In [22]:
data_Set3.dropna(axis =0, inplace=True)

In [23]:
data_Set3

,instant,dteday,season,yr,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,620,2011-01-29,1,0,1,1,False,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,621,2011-01-29,1,0,1,2,False,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,622,2011-01-29,1,0,1,3,False,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,623,2011-01-29,1,0,1,4,False,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,624,2011-01-29,1,0,1,6,False,6,1,0.16,0.1818,0.64,0.1343,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,615,2011-01-28,1,0,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
386,616,2011-01-28,1,0,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
387,617,2011-01-28,1,0,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
388,618,2011-01-28,1,0,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
389,619,2011-01-29,1,0,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [24]:
data_Set3.drop(['yr'], axis=1)

,instant,dteday,season,mnth,hr,holiday,weekday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,620,2011-01-29,1,1,1,False,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,621,2011-01-29,1,1,2,False,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,622,2011-01-29,1,1,3,False,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,623,2011-01-29,1,1,4,False,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,624,2011-01-29,1,1,6,False,6,1,0.16,0.1818,0.64,0.1343,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,615,2011-01-28,1,1,20,False,5,2,0.24,0.2273,0.70,0.1940,1,61,62
386,616,2011-01-28,1,1,21,False,5,2,0.22,0.2273,0.75,0.1343,1,57,58
387,617,2011-01-28,1,1,22,False,5,1,0.24,0.2121,0.65,0.3582,0,26,26
388,618,2011-01-28,1,1,23,False,5,1,0.24,0.2273,0.60,0.2239,1,22,23
389,619,2011-01-29,1,1,0,False,6,1,0.22,0.1970,0.64,0.3582,2,26,28

**Combining previous dataset with the New dataset (dataset 3)**

In [25]:
final_dataset = pd.merge(new_data, data_Set3, on='holiday', how='inner')

In [29]:
final_dataset.head()

,Unnamed: 0_x,instant_x,dteday_x,season_x,yr_x,mnth_x,hr_x,holiday,weekday_x,weathersit_x,...,hr_y,weekday_y,weathersit_y,temp_y,atemp_y,hum_y,windspeed_y,casual_y,registered_y,cnt_y
0,0,1,2011-01-01,1,0,1,0,False,6,1,...,1,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,0,1,2011-01-01,1,0,1,0,False,6,1,...,2,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,0,1,2011-01-01,1,0,1,0,False,6,1,...,3,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,0,1,2011-01-01,1,0,1,0,False,6,1,...,4,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,0,1,2011-01-01,1,0,1,0,False,6,1,...,6,6,1,0.16,0.1818,0.64,0.1343,0,2,2

In [26]:
final_dataset.head(20)

,Unnamed: 0_x,instant_x,dteday_x,season_x,yr_x,mnth_x,hr_x,holiday,weekday_x,weathersit_x,...,hr_y,weekday_y,weathersit_y,temp_y,atemp_y,hum_y,windspeed_y,casual_y,registered_y,cnt_y
0,0,1,2011-01-01,1,0,1,0,False,6,1,...,1,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,0,1,2011-01-01,1,0,1,0,False,6,1,...,2,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,0,1,2011-01-01,1,0,1,0,False,6,1,...,3,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,0,1,2011-01-01,1,0,1,0,False,6,1,...,4,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,0,1,2011-01-01,1,0,1,0,False,6,1,...,6,6,1,0.16,0.1818,0.64,0.1343,0,2,2
5,0,1,2011-01-01,1,0,1,0,False,6,1,...,7,6,1,0.16,0.1818,0.59,0.1045,1,4,5
6,0,1,2011-01-01,1,0,1,0,False,6,1,...,8,6,1,0.18,0.1970,0.55,0.1642,3,31,34
7,0,1,2011-01-01,1,0,1,0,False,6,1,...,9,6,1,0.18,0.2121,0.59,0.0896,0,34,34
8,0,1,2011-01-01,1,0,1,0,False,6,1,...,10,6,2,0.18,0.2121,0.64,0.1045,4,51,55
9,0,1,2011-01-01,1,0,1,0,False,6,1,...,11,6,2,0.18,0.1970,0.64,0.1343,4,60,64
10,0,1,2011-01-01,1,0,1,0,False,6,1,...,12,6,2,0.20,0.1970,0.59,0.1940,12,66,78
11,0,1,2011-01-01,1,0,1,0,False,6,1,...,13,6,2,0.22,0.2273,0.55,0.1642,9,56,65
12,0,1,2011-01-01,1,0,1,0,False,6,1,...,14,6,2,0.22,0.2273,0.60,0.1343,10,89,99
13,0,1,2011-01-01,1,0,1,0,False,6,1,...,15,6,1,0.22,0.2121,0.69,0.2537,22,98,120
14,0,1,2011-01-01,1,0,1,0,False,6,1,...,16,6,1,0.24,0.2424,0.60,0.1642,19,88,107
15,0,1,2011-01-01,1,0,1,0,False,6,1,...,17,6,1,0.24,0.2879,0.60,0.0000,9,82,91
16,0,1,2011-01-01,1,0,1,0,False,6,1,...,18,6,1,0.22,0.2273,0.69,0.1343,9,59,68
17,0,1,2011-01-01,1,0,1,0,False,6,1,...,19,6,2,0.22,0.2121,0.69,0.2537,6,52,58
18,0,1,2011-01-01,1,0,1,0,False,6,1,...,20,6,1,0.18,0.2121,0.74,0.0896,1,42,43
19,0,1,2011-01-01,1,0,1,0,False,6,1,...,21,6,1,0.18,0.2121,0.74,0.0896,1,35,36

In [27]:
final_dataset.shape

(228540, 33)

In [30]:
final_dataset.isnull().sum()

Unnamed: 0_x       0
instant_x          0
dteday_x           0
season_x           0
yr_x               0
mnth_x             0
hr_x               0
holiday            0
weekday_x          0
weathersit_x       0
temp_x             0
Unnamed: 0_y       0
atemp_x         4290
hum_x              0
windspeed_x        0
casual_x           0
registered_x       0
cnt_x              0
instant_y          0
dteday_y           0
season_y           0
yr_y               0
mnth_y             0
hr_y               0
weekday_y          0
weathersit_y       0
temp_y             0
atemp_y            0
hum_y              0
windspeed_y        0
casual_y           0
registered_y       0
cnt_y              0
dtype: int64

In [31]:
final_dataset.isnull().sum().sum()

4290

In [32]:
df1 = final_dataset.fillna(value =0 )
df1

,Unnamed: 0_x,instant_x,dteday_x,season_x,yr_x,mnth_x,hr_x,holiday,weekday_x,weathersit_x,...,hr_y,weekday_y,weathersit_y,temp_y,atemp_y,hum_y,windspeed_y,casual_y,registered_y,cnt_y
0,0,1,2011-01-01,1,0,1,0,False,6,1,...,1,6,1,0.22,0.2273,0.64,0.1940,0,20,20
1,0,1,2011-01-01,1,0,1,0,False,6,1,...,2,6,1,0.22,0.2273,0.64,0.1642,0,15,15
2,0,1,2011-01-01,1,0,1,0,False,6,1,...,3,6,1,0.20,0.2121,0.64,0.1343,3,5,8
3,0,1,2011-01-01,1,0,1,0,False,6,1,...,4,6,1,0.16,0.1818,0.69,0.1045,1,2,3
4,0,1,2011-01-01,1,0,1,0,False,6,1,...,6,6,1,0.16,0.1818,0.64,0.1343,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228535,609,610,2011-01-28,1,0,1,15,False,5,2,...,20,5,2,0.24,0.2273,0.70,0.1940,1,61,62
228536,609,610,2011-01-28,1,0,1,15,False,5,2,...,21,5,2,0.22,0.2273,0.75,0.1343,1,57,58
228537,609,610,2011-01-28,1,0,1,15,False,5,2,...,22,5,1,0.24,0.2121,0.65,0.3582,0,26,26
228538,609,610,2011-01-28,1,0,1,15,False,5,2,...,23,5,1,0.24,0.2273,0.60,0.2239,1,22,23
228539,609,610,2011-01-28,1,0,1,15,False,5,2,...,0,6,1,0.22,0.1970,0.64,0.3582,2,26,28

In [33]:
df1.isnull().sum()

Unnamed: 0_x    0
instant_x       0
dteday_x        0
season_x        0
yr_x            0
mnth_x          0
hr_x            0
holiday         0
weekday_x       0
weathersit_x    0
temp_x          0
Unnamed: 0_y    0
atemp_x         0
hum_x           0
windspeed_x     0
casual_x        0
registered_x    0
cnt_x           0
instant_y       0
dteday_y        0
season_y        0
yr_y            0
mnth_y          0
hr_y            0
weekday_y       0
weathersit_y    0
temp_y          0
atemp_y         0
hum_y           0
windspeed_y     0
casual_y        0
registered_y    0
cnt_y           0
dtype: int64